- hosts: all
  tasks:
    - name: Ping
      ansible.builtin.ping:

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
          - sudo
          - curl
          - fail2ban
        #name: nginx=1.18.0
        state: latest
        update_cache: yes

    - name: Elimina lista de paquetes
      ansible.builtin.apt:
        pkg:
          - vagrant
        state: absent

    - name: Upgrade the OS (apt-get dist-upgrade)
      ansible.builtin.apt:
        upgrade: dist