---
# Estado: Playbook probada y funcionando
# Autor: Luis Ferreira
# Comentario: 
#  - hosts debe coincidir con el aula
#
- name: Ping Windows hosts
  hosts: sys1
  tasks:
    - name: Test connectivity
      ansible.windows.win_ping:
