---
- name: Reemplazar usuario local de Windows 11
  hosts: windows
  gather_facts: false

  vars:
    usuario_antiguo: "usuario_viejo"
    usuario_nuevo: "usuario_nuevo"
    password_nuevo: "Cambiar_Esta_Password_123!"
    nuevo_usuario_es_admin: true

  tasks:

    - name: Comprobar si existe el usuario antiguo
      ansible.windows.win_user:
        name: "{{ usuario_antiguo }}"
        state: query
      register: usuario_existente

    - name: Eliminar usuario antiguo
      ansible.windows.win_user:
        name: "{{ usuario_antiguo }}"
        state: absent
        remove: true
      when: usuario_existente.exists | default(false)

    - name: Eliminar el perfil del usuario antiguo si todavía existe
      ansible.windows.win_powershell:
        script: |
          $username = "{{ usuario_antiguo }}"

          $profile = Get-CimInstance Win32_UserProfile |
            Where-Object {
              $_.LocalPath -like "C:\Users\$username"
            }

          if ($profile) {
              Remove-CimInstance -InputObject $profile
          }
      when: usuario_existente.exists | default(false)

    - name: Crear nuevo usuario local
      ansible.windows.win_user:
        name: "{{ usuario_nuevo }}"
        password: "{{ password_nuevo }}"
        state: present
        password_never_expires: true
        user_cannot_change_password: false

    - name: Añadir nuevo usuario al grupo Administradores
      ansible.windows.win_group_membership:
        name: Administradores
        members:
          - "{{ usuario_nuevo }}"
        state: present
      when: nuevo_usuario_es_admin | bool
